[api]
dashboard = true

[entryPoints]
[entryPoints.web]
address = ":80"

[entryPoints.web-secure]
address = ":443"

[certificatesResolvers.le.acme]
email = "eaksu94@gmail.com"
storage = "acme.json"
[certificatesResolvers.le.acme.httpChallenge]
entryPoint = "web"

[providers]
[providers.docker]
Watch = true
ExposedByDefault = false
endpoint = "unix:///var/run/docker.sock"
