version: '3.7'

services:
  reverse-proxy:
    image: traefik

  postgresql:
    image: postgres:14
    volumes:
      - dbdata:/var/lib/postgresql/data

  rabbitmq:
    image: 'rabbitmq:3-management-alpine'

  redis:
    image: redis:alpine

  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.16.0'
    volumes:
      - esdata:/usr/share/elasticsearch/data

  logstash:
    image: 'docker.elastic.co/logstash/logstash:7.16.0'
    depends_on:
      - elasticsearch

  kibana:
    image: 'docker.elastic.co/kibana/kibana:7.16.0'
    depends_on:
      - elasticsearch

volumes:
  dbdata:
  esdata: