apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
spec:
  version: 7.16.2
  nodeSets:
    - name: default
      count: 1
      podTemplate:
        spec:
          containers:
            - name: elasticsearch
              env:
                - name: ES_JAVA_OPTS
                  value: "-Xms512m -Xmx512m"
              volumeMounts:
                - name: esdata
                  mountPath: /usr/share/elasticsearch/data
              resources:
                requests:
                  memory: 1Gi
                  cpu: 1
                limits:
                  memory: 2Gi
                  cpu: 2
          volumes:
            - name: esdata
              persistentVolumeClaim:
                claimName: esdata
      config:
        node.store.allow_mmap: false
  http:
    tls:
      selfSignedCertificate:
        disabled: true