apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-service
spec:
  selector:
    matchLabels:
      app: identity-service
  replicas: 1
  template:
    metadata:
      labels:
        app: identity-service
    spec:
      containers:
        - name: identity-service
          image: ${DOCKER_IMAGE_PREFIX}/identity-service:${DOCKER_IMAGE_TAG}
          imagePullPolicy: "Always"
          env:
            - name: DOTNET_APP
              value: MicroserviceDemo.IdentityService.HttpApi.Host
            - name: ConnectionStrings__IdentityService
              value: Host=postgresql;Port=5432;Database=MicroserviceDemo_Identity;User ID=postgres;Password=${DEMO_SQL_PASSWORD}
            - name: ConnectionStrings__AdministrationService
              value: Host=postgresql;Port=5432;Database=MicroserviceDemo_Administration;User ID=postgres;Password=${DEMO_SQL_PASSWORD}
            - name: Redis__Configuration
              value: redis
            - name: RabbitMQ__Connections__Default__HostName
              value: rabbitmq
            - name: RabbitMQ__Connections__Default__UserName
              value: ""
            - name: RabbitMQ__Connections__Default__Password
              value: ""
            - name: ElasticSearch__Url
              value: http://elastic:${DEMO_ELASTICSEARCH_PASSWORD}@elasticsearch:9200
            - name: AuthServer__Authority
              value: https://account.${DEMO_DOMAIN}
            - name: IdentityClients__Default__Authority
              value: https://account.${DEMO_DOMAIN}
            - name: App__SelfUrl
              value: https://identity-service.${DEMO_DOMAIN}
            - name: App__CorsOrigins
              value: https://*.${DEMO_DOMAIN}
            - name: RemoteServices__AbpIdentity__BaseUrl
              value: http://identity-service
            - name: IdentityServerClients__Web__RootUrl
              value: https://${DEMO_DOMAIN}
            - name: IdentityServerClients__WebGateway__RootUrl
              value: https://web-gateway.${DEMO_DOMAIN}
            - name: IdentityServerClients__AccountService__RootUrl
              value: https://account.${DEMO_DOMAIN}
            - name: IdentityServerClients__IdentityService__RootUrl
              value: https://identity-service.${DEMO_DOMAIN}
            - name: IdentityServerClients__AdministrationService__RootUrl
              value: https://administration-service.${DEMO_DOMAIN}
            - name: IdentityServerClients__ContactService__RootUrl
              value: https://contact-service.${DEMO_DOMAIN}
            - name: IdentityServerClients__ReportService__RootUrl
              value: https://report-service.${DEMO_DOMAIN}
            - name: KnownProxies__0
              value: 10.43.0.0/16
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: "${DOCKER_IMAGE_SECRETNAME}"