apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: web
  replicas: 1
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: ${DOCKER_IMAGE_PREFIX}/web:${DOCKER_IMAGE_TAG}
          imagePullPolicy: "Always"
          env:
            - name: DOTNET_APP
              value: MicroserviceDemo.Web
            - name: Redis__Configuration
              value: redis
            - name: RabbitMQ__Connections__Default__HostName
              value: rabbitmq
            - name: ElasticSearch__Url
              value: http://elastic:${DEMO_ELASTICSEARCH_PASSWORD}@elasticsearch:9200
            - name: AuthServer__Authority
              value: https://account.${DEMO_DOMAIN}
            - name: App__SelfUrl
              value: https://${DEMO_DOMAIN}
            - name: RemoteServices__Default__BaseUrl
              value: http://web-gateway
            - name: KnownProxies__0
              value: 10.43.0.0/16
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: "${DOCKER_IMAGE_SECRETNAME}"